# Hamoye Stage A Quiz

## Importing the required libraries

In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Getting the data from the Git Hub Repository

In [3]:
url = 'https://bit.ly/HDSC-StageOneDataset'
df = pd.read_csv(url)

## Exploring the data

In [37]:
df.describe()

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

In [38]:
df.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

## Question 1

In [6]:
A = [1,2,3,4,5,6]
B = [13,21,34]

In [39]:
A_B = A.extend(B)
print(A_B)

None


In [40]:
A_B = A.append(B)

In [41]:
print(A_B)

None


## Question 2

In [47]:
try:
    print (np.identity(3))
except:
    print ('Invalid Python Statement')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
try:
    print(np.array([1,0,0],[0,1,0],[0,0,1]))
except:
    print('Invalid Python Statement')

Invalid Python Statement


In [49]:
try:
    print(eye(3))
except:
    print ('Invalid Python Statement')

Invalid Python Statement


## Question 3

In [53]:
#Which of the fuel type code has the lowest average fuel cost per unit burned
df.groupby('fuel_type_code_pudl').mean().sort_values(ascending = True, by = 'fuel_cost_per_unit_burned')[:1]

utility_id_ferc1  report_year  fuel_qty_burned  \
fuel_type_code_pudl                                                   
gas                        124.122062   2005.97806     4.843183e+06   

                     fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
fuel_type_code_pudl                                                   
gas                             1.021913                  13.659397   

                     fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
fuel_type_code_pudl                                                     
gas                                     12.095172             5.408876

## Question 4

### What is the standard deviation and 75th percentile of the measure of energy per unit (fuel_mmbtu_per_unit) in two decimal places

In [58]:
print('The Standard deviation for fuel_mmbtu_per_unit is:', round(df.describe().loc['std','fuel_mmbtu_per_unit'],2))
print('The 75th percentile for fuel_mmbtu_per_unit is:', round(df.describe().loc['75%','fuel_mmbtu_per_unit'],2))

The Standard deviation for fuel_mmbtu_per_unit is: 10.6
The 75th percentile for fuel_mmbtu_per_unit is: 17.01


## Question 5

### What is the skewness and kurtosis for the fuel quantity burned in two decimal places

In [60]:
from scipy.stats import skew
from scipy.stats import kurtosis

print ('The skewness for the fuel quantity burned is:',round(skew(df['fuel_qty_burned']),2))
print ('The kurtosis for the fuel quantity burned is:',round(kurtosis(df['fuel_qty_burned']),2))

The skewness for the fuel quantity burned is: 15.85
The kurtosis for the fuel quantity burned is: 651.26


## Question 6

### Which feature has missing values and what is the total number of missing value and percentage of the missing rows as a factor of the total number of rows in three decimal places

In [62]:
#Row containing missing data
df.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [64]:
# Number of missing data
print('The number of missing data in the fuel unit feature is',df.isnull().sum()['fuel_unit'])

The number of missing data in the fuel unit feature is 180


In [65]:
# Total number of rows in the dataframe
df.shape[0]

29523

In [66]:
#Percentage of missing data
print('The percentage of missing data in the dataframe to three decimal places is',round((df.isnull().sum()['fuel_unit']/df.shape[0])*100,3))

The percentage of missing data in the dataframe to three decimal places is 0.61


## Question 7

## The feature with missing values falls under what category?

In [68]:
print('The data type of fuel unit is:',df['fuel_unit'].dtype,'or categorical data')

The data type of fuel unit is: object or categorical data


## Question 8

### Which of the features has the second and third lowest correlation with the fuel cost per unit burned

In [69]:
(((df.corr()['fuel_cost_per_unit_burned'])).sort_values(ascending = True))[1:3]

fuel_qty_burned       -0.018535
fuel_mmbtu_per_unit   -0.010034
Name: fuel_cost_per_unit_burned, dtype: float64

# Question 9

### For the fuel type coal, what is the percentage change in the fuel cost per unit burned in 1998 compared to 1994

In [70]:
perc_change = (df.groupby(['fuel_type_code_pudl','report_year']).sum().loc['coal']).loc[[1994,1998],['fuel_cost_per_unit_burned']]

In [71]:
perc_change

fuel_cost_per_unit_burned
report_year                           
1994                         14984.572
1998                         11902.597

In [76]:
print('The percentage in fuel cost per unit burned in 1998 compared to 1994 is:',round(((perc_change.at[1998,'fuel_cost_per_unit_burned'] - perc_change.at[1994,'fuel_cost_per_unit_burned'])/perc_change.at[1994,'fuel_cost_per_unit_burned'])*100))

The percentage in fuel cost per unit burned in 1998 compared to 1994 is: -21.0


## Question 10

### Which year has the highest average fuel cost per unit delivered 

In [77]:
df.groupby('report_year').mean().sort_values(ascending = False, by = 'fuel_cost_per_unit_delivered')[:1]

utility_id_ferc1  fuel_qty_burned  fuel_mmbtu_per_unit  \
report_year                                                           
1997               108.366545     2.813503e+06            10.247632   

             fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
report_year                                                            
1997                        149.482132                  11140.197239   

             fuel_cost_per_mmbtu  
report_year                       
1997                    3.113486